package-lock.json
package.json
src/__test__/export.test.ts
src/lib/__test__/string.test.ts
src/lib/data/content.ts
src/lib/data/site.ts
src/lib/string.ts

Add `titleCase()` string helper method

Expose tag filter in content API

---

entry.css
package-lock.json
package.json
src/components/Renderer/__test__/__snapshots__/RendererContent.test.tsx.snap
src/components/Renderer/code_block.tsx

Wrap `SyntaxHighlighter` so we can apply our own styling.
Remove unused styles.

Fix notice, blockquote and code block margins

---

package-lock.json
package.json
src/lib/types/__stories__/Site.README.md
src/lib/types/site.ts

this is especially useful for blog sites.

Add site homepage tags

---

package-lock.json
package.json
src/components/Renderer/__stories__/Renderer.stories.tsx
src/components/Renderer/__test__/RendererContent.test.tsx
src/components/Renderer/__test__/__snapshots__/RendererContent.test.tsx.snap
src/components/Renderer/content.tsx
src/components/Renderer/iframe.tsx

- Be smart about calculating Youtube poster width since they are specific predefined sizes. Fix a few missing img sizes
- 1.0.4

Be smart about Youtube poster image / background width

---

package-lock.json
package.json
src/components/Renderer/content.tsx
src/components/Renderer/iframe.tsx
src/lib/file_metadata.ts

- fix using youtube placeholder as cover
- 1.0.5

Youtube cover image default size

---

base.css
defaultTheme.css
entry.css
package-lock.json
package.json
src/components/Renderer/__data__/simple_error_notice.ts
src/components/Renderer/__data__/simple_info_notice.ts
src/components/Renderer/__data__/simple_warning_notice.ts
src/components/Renderer/__test__/__snapshots__/RendererContent.test.tsx.snap

Accessibility contrast fixes

---

package-lock.json
package.json
src/components/Documentation/Page/__test__/__snapshots__/DocumentationHome.test.tsx.snap
src/components/Documentation/Page/__test__/__snapshots__/DocumentationSearchResults.test.tsx.snap
src/components/Footer/__test__/__snapshots__/Footer.test.tsx.snap
src/components/Header/__test__/__snapshots__/Header.test.tsx.snap
src/components/Page/__test__/__snapshots__/PageDashboard.test.tsx.snap
src/components/Page/__test__/__snapshots__/PageEntry.test.tsx.snap
src/components/Page/__test__/__snapshots__/PageError.test.tsx.snap
src/components/Prebuilt/__test__/__snapshots__/PrebuiltEntry.test.tsx.snap
src/components/Prebuilt/__test__/__snapshots__/PrebuiltError.test.tsx.snap
src/components/Prebuilt/__test__/__snapshots__/PrebuiltHeader.test.tsx.snap
src/components/Prebuilt/__test__/__snapshots__/PrebuiltHome.test.tsx.snap
src/components/Prebuilt/__test__/__snapshots__/PrebuiltSearchResults.test.tsx.snap
src/components/Subscribe/__test__/__snapshots__/Subscribe.test.tsx.snap
src/components/Subscribe/index.tsx

- Attempt to resolve Lighthouse issue: Avoid non-composited animations
- 1.0.8

Attempt to resolve Lighthouse issue: Avoid non-composited animations

---

package-lock.json
package.json
src/components/Pinpoint/index.ts
src/components/Renderer/iframe.tsx

- Attempt to fix Youtube player button accessibility
- 1.0.9

Attempt to fix Youtube player button accessibility

---

package-lock.json
package.json
src/components/Head/SEO/__test__/SEO.test.tsx
src/components/Head/SEO/__test__/__snapshots__/SEO.test.tsx.snap
src/components/Head/SEO/index.tsx
src/components/Prebuilt/__data__/testSite.json
src/lib/types/site.ts

- Add support for private visibility which disables search index index
- 1.0.11

Add support for private visibility which disables search index index

---

package-lock.json
package.json
src/components/Head/SEO/__test__/SEO.test.tsx
src/components/Head/SEO/__test__/__snapshots__/SEO.test.tsx.snap
src/components/Head/SEO/index.tsx
src/lib/types/content.ts

- Add support for page level robots override
- 1.0.12

Add ability to change the SEO robots visibility at the page level

---

package-lock.json
package.json
src/__test__/export.test.ts
src/components/Head/SEO/__test__/__snapshots__/SEO.test.tsx.snap
src/components/Head/SEO/index.tsx
src/components/Head/__test__/__snapshots__/Head.test.tsx.snap
src/components/Head/index.tsx
src/components/Prebuilt/Footer/index.tsx
src/components/Prebuilt/__data__/testSite.json
src/lib/__test__/router.ts
src/lib/fetch.ts
src/lib/index.ts
src/lib/router.ts
src/lib/types/site.ts

- Add support for basePath. Add fetch retry logic
- 1.0.17

Add support for basePath. Add fetch retry logic

---

package-lock.json
package.json
src/components/Documentation/Prebuilt/Home/index.tsx
src/components/Pinpoint/index.ts
src/components/Prebuilt/Entry/index.tsx

- Add ability to pass the basePath to startTracking
- 1.0.18

start tracking base path

---

package-lock.json
package.json
src/components/Head/__test__/Head.test.tsx
src/components/Head/__test__/__snapshots__/Head.test.tsx.snap
src/components/Head/index.tsx

- more base path fixes
- 1.0.19

more base path

---

package-lock.json
package.json
src/lib/__test__/router.test.ts
src/lib/router.ts

- Fix up basepath test cases, rename test file etc
- 1.0.21

more basepath tests

---

package-lock.json
package.json
src/lib/__test__/router.test.ts
src/lib/router.ts

- More basepath variations when origins are different for testing local
- 1.0.22

basepath origin

---

package-lock.json
package.json
src/lib/__test__/router.test.ts
src/lib/router.ts

- Add more test case for determining the relative path
- 1.0.23

relative path test cases

---

package-lock.json
package.json
src/components/Renderer/text.tsx

Render newly added marks `bold`, `italic` and `code`.

Add missing marks to renderer

---

entry.css
package-lock.json
package.json
src/components/Renderer/__test__/__snapshots__/RendererContent.test.tsx.snap
src/components/Renderer/code_block.tsx

- CHA-518 add copy to clipboard to code blocks
- 1.0.27

Add copy to clipboard for code blocks

---

package-lock.json
package.json
src/components/Renderer/__data__/video_file_api.ts
src/components/Renderer/__stories__/Renderer.stories.tsx
src/components/Renderer/__test__/RendererContent.test.tsx
src/components/Renderer/__test__/__snapshots__/RendererContent.test.tsx.snap
src/components/Renderer/file.tsx
src/components/Renderer/image_block.tsx

- For File API based video urls, support automated negotiated content types for optimized video formats
- 1.0.30
- For File API based video urls, support automated negotiated content types for optimized video formats

For File API based video urls, support automated negotiated content types for optimized video formats

---

base.css
package-lock.json
package.json
src/components/Renderer/__data__/audio_files.ts
src/components/Renderer/__stories__/Renderer.stories.tsx
src/components/Renderer/__test__/RendererContent.test.tsx
src/components/Renderer/__test__/__snapshots__/RendererContent.test.tsx.snap
src/components/Renderer/content.tsx
src/components/Renderer/file.tsx

- Add support for audio, add negotiated source types for Cover Media
- 1.0.31

Add support for video and add negotiated video types for CoverMedia

---

package-lock.json
package.json
src/components/Card/__test__/__snapshots__/CardContainer.test.tsx.snap
src/components/Page/__test__/__snapshots__/PageEntry.test.tsx.snap
src/components/Prebuilt/__test__/__snapshots__/PrebuiltEntry.test.tsx.snap
src/components/Prebuilt/__test__/__snapshots__/PrebuiltHome.test.tsx.snap
src/components/Prebuilt/__test__/__snapshots__/PrebuiltSearchResults.test.tsx.snap
src/components/Sidebar/__test__/__snapshots__/Sidebar.test.tsx.snap
src/components/Tags/__test__/__snapshots__/TagBar.test.tsx.snap
src/components/Tags/__test__/__snapshots__/TagItem.test.tsx.snap
src/lib/__test__/color.test.ts
src/lib/color.ts

- Fix issue with tag colors getting penalized because of contrast ratio issues
- 1.0.35

Fix issue with tag colors getting penalized because of contrast ratio issues

---

package-lock.json
package.json
src/__test__/export.test.ts
src/index.ts

- Export our Image component
- 1.0.36

Export our Image component

---

package-lock.json
package.json
src/components/Prebuilt/Home/index.tsx
src/components/Prebuilt/__test__/PrebuiltHome.test.tsx

- We need to client side fetch analytics to get the latest and greatest since they will be cached for SSR
- 1.0.37

We need to client side fetch analytics to get the latest and greatest since they will be cached for SSR

---

base.css
package-lock.json
package.json
src/components/Banner/__stories__/Banner.stories.tsx
src/components/Banner/__test__/Banner.test.tsx
src/components/Banner/__test__/__snapshots__/Banner.test.tsx.snap
src/components/Banner/index.tsx

- Add support for Banner to be styled and to be closeable
- 1.0.39

Add support for Banner to be styled and to be closeable

---

package-lock.json
package.json
src/components/Banner/__stories__/Banner.stories.tsx
src/components/Banner/index.tsx

- Add ablity to get callback when closing Banner
- 1.0.40

Add ablity to get callback when closing Banner

---

package-lock.json
package.json
src/components/Modal/index.tsx
src/components/Page/Entry/index.tsx
src/components/Pinpoint/index.tsx
src/components/Prebuilt/Entry/index.tsx
src/components/Prebuilt/__test__/__snapshots__/PrebuiltEntry.test.tsx.snap
src/lib/types/feedback.ts
src/widgets/Feedback/__stories__/Feedback.stories.tsx
src/widgets/Feedback/index.tsx
src/widgets/Feedback/style.css
src/widgets/FeedbackModal/__stories__/FeedbackModal.stories.tsx
src/widgets/FeedbackModal/index.tsx
src/widgets/FeedbackModal/style.css

- Expose Feedback Modal and some UI improvements from integration into designer
- 3.0.3

Expose Feedback Modal and some UI improvements from integration into designer

---

package-lock.json
package.json
src/widgets/FeedbackModal/index.tsx
src/widgets/FeedbackModal/style.css

- Feedback Modal should have a different classname from Feedback
- 3.0.4

Feedback Modal should have a different classname from Feedback

---

package-lock.json
package.json
src/widgets/FeedbackModal/style.css

- More Feedback modal css tweaks
- 3.0.5

feedback modal style fixes

---

package-lock.json
package.json
rollup.config.js

- Turn off built-ins to attempt to fix issue with tty module trying to be loaded
- 3.0.6
https://github.com/sveltejs/sapper/issues/755

attempt to fix tty issue

---

package-lock.json
package.json
rollup.config.js
src/lib/fetch.ts
src/lib/hooks/useContent/index.ts
src/lib/hooks/useEntries/index.ts

- Attempt to fix issue where a module that uses fetch tries to bring in node-fetch instead of unfetch
- 3.0.7

fetch issues

---

package-lock.json
package.json
rollup.config.js
src/lib/fetch.ts

- Try and trick the module into working ...?
- 3.0.8

more fetch

---

package-lock.json
package.json
rollup.config.js

- Alias debug to force load the browser version
- 3.0.9

Alias debug to force load the browser version

---

package-lock.json
package.json
rollup.config.js

- remove some previous changes to see if this works and debug it
- 3.0.11

debug process error

---

package-lock.json
package.json
rollup.config.js
src/components/Modal/index.tsx

Cleanup from testing now that it works 👯‍♂️

---

package-lock.json
package.json
src/components/Modal/index.tsx

- Add zIndex on the modal backing container as well
- 3.1.1

Add zIndex on the modal backing container as well

---

package-lock.json
package.json
src/lib/data/feedback.ts
src/lib/fetch.ts
src/lib/hooks/useFeedback/index.ts
src/lib/index.ts
src/lib/subscription.ts
src/widgets/FeedbackModal/index.tsx

- Improve feedback with error check, add in url, page title if not specififed, set cookie on result if sent
- 3.1.2

feedback improvements

---

package-lock.json
package.json
src/components/Head/ScriptPlugins/index.tsx
src/components/Head/ScriptPlugins/typekit.tsx

- adds support for typekit as a script plugin

Add typekit support

---

base.css
package-lock.json
package.json

- Remove the feedback wrapper shadow since the widget has its own
- 3.1.9

Remove the feedback wrapper shadow since the widget has its own

---

base.css
package-lock.json
package.json
src/components/Documentation/Prebuilt/Home/index.tsx
src/components/Documentation/Prebuilt/__test__/__snapshots__/PrebuiltDocumentationHome.test.tsx.snap
src/components/Documentation/Prebuilt/__test__/__snapshots__/PrebuiltDocumentationSearchResults.test.tsx.snap
src/components/Footer/index.tsx
src/components/Page/Roadmap/index.tsx
src/components/Prebuilt/Entry/index.tsx
src/components/Prebuilt/Footer/index.tsx
src/components/Prebuilt/Roadmap/index.tsx
src/components/Prebuilt/__stories__/PrebuiltFooter.stories.tsx
src/components/Prebuilt/__test__/__snapshots__/PrebuiltEntry.test.tsx.snap
src/components/Prebuilt/__test__/__snapshots__/PrebuiltError.test.tsx.snap
src/components/Prebuilt/__test__/__snapshots__/PrebuiltFooter.test.tsx.snap
src/components/Prebuilt/__test__/__snapshots__/PrebuiltHome.test.tsx.snap
src/components/Prebuilt/__test__/__snapshots__/PrebuiltRoadmap.test.tsx.snap
src/components/Prebuilt/__test__/__snapshots__/PrebuiltSearchResults.test.tsx.snap
src/components/Vote/index.tsx
src/lib/data/feedback.ts
src/widgets/Feedback/index.tsx

- Small improvements to the Roadmap voting UI for Modal
- Fix small screen roadmap breakpoint
- Add Roadmap link in footer
- Add Feedback to Roadmap page
- 3.1.11

Small visual tweaks to the Roadmap

---

base.css
package-lock.json
package.json

- Only add margin to roadmap feedback in larger screen
- 3.1.12

roadmap feedback footer tweaks
